### ISSUE TITLE
Mermaid Diagrams Not Width Bound

### ISSUE THREAD

**Issue by Willowlark** [DubininDmitry/Obuntu#3]
Hey there. Love the theme, but having an issue where mermaid diagrams don't get restricted to the same width as the rest of the docuemnt. It makes them very hard to read. I don't know enough CSS to make the adjustment myself, but would love it if you had a fix I could add!

![image](https://user-images.githubusercontent.com/4207813/124511359-ef5a1c80-dda3-11eb-86e8-2206993a00ad.png)

![image](https://user-images.githubusercontent.com/4207813/124511383-fa14b180-dda3-11eb-9f0b-6ac10db03ca5.png)

**Comment by dmytrodubinin** [comment]
Thanks for feedback. Could you attach an example of a document where this problem is observed? In my use, I do not observe such a problem
![image](https://user-images.githubusercontent.com/8066458/125249221-82cfa800-e2e4-11eb-9a76-eb77422c149c.png)

**Comment by Willowlark** [comment]
[Test.md](https://github.com/DubininDmitry/Obuntu-theme-for-Obsidian/files/6856974/Test.md)

![image](https://user-images.githubusercontent.com/4207813/126517023-be3d95d1-60d9-4862-9eb6-99ff9d57911b.png)

**Comment by dmytrodubinin** [comment]
This is the standard behavior of the application, the problem is not in my theme. Here is the screenshot of your file when the default Obsidian theme is enabled.
Bag need to send Obsidian developers
![image](https://user-images.githubusercontent.com/8066458/126746128-5aaba38c-303c-4a90-b266-6944ce1e2d5c.png)
