### ISSUE TITLE
Allow for empty lines in Quote blocks

### ISSUE THREAD

**Issue by Willowlark** [DubininDmitry/Obuntu#4]
When creating a quote block like so:

```
> Text here
>
> More text here
```

Obuntu does not allow for the blank line to serve as a newline within the quote block. If you try to insert multiple blank lines, they flatten down to one. This all causes the text to appear like  ```Text here More text here``` inside the quote, rather than the spaced out variant. The only alternative is to have them as two separate quotes, which makes little sense for multiple paragraph quotes. 

I believe it has something to do with the way the quote images appear in the quote block (love that detail though) but I couldn't isolate what actually causes it to happen.

**Comment by dmytrodubinin** [comment]
If you put a quote icon, it turns out ugly design. Therefore, I decided to save the standard make of the quotation, saving my colors.
I hope this option will satisfy you.
Please update the subject in yourself

If keep quote icons:
![image](https://user-images.githubusercontent.com/8066458/126748148-fc17b652-1904-412c-9cc3-879d74761d53.png)

Current fixed styles:
![image](https://user-images.githubusercontent.com/8066458/126748491-fe5a7fbb-5e25-4cf3-be03-72d339c2f3bc.png)
